formatter: "markdown"

version: ""

header-from: main.tf
footer-from: ""

recursive:
  enabled: false
  path: modules

sections:
  hide: []
  show: []

content: ""

output:
  file: "README.md"
  mode: inject
  template: |-
    <!-- BEGIN_TF_DOCS -->
    # Quick AWS ECS Fargate Service

    [![License: MIT](https://img.shields.io/badge/License-MIT-yellow.svg)](https://opensource.org/licenses/MIT)

    Terraform project which create VPC, ALB and ECS Fargate Service resource on AWS from scratch.

    ## *Create and destroy the infrastructure*

    ### 1. Create infrastructure

    ```shell
    git clone https://github.com/mbasri/quick-aws-ecs-fargate-service.git
    cd quick-aws-ecs-fargate-service
    terraform init
    terraform apply
    ```

    ### 2. Destroy infrastructure

    ```shell
    git clone https://github.com/mbasri/quick-aws-ecs-fargate-service.git
    cd quick-aws-ecs-fargate-service
    terraform init
    terraform destroy
    ```

    ## *Use the ECS Fargate Service*

    ### 1. API call

    See the Terrafom output 'api_url' to call the API

    ## *Generate docs*
    
    ```shell
    terraform-docs -c .terraform-docs.yml .
    ```

    {{ .Content }}

    ## *Author*

    * [**Mohamed BASRI**](https://github.com/mbasri)

    ## *License*

    This is free and unencumbered software released into the public domain - see the [LICENSE](./LICENSE) file for details

    <!-- END_TF_DOCS -->

output-values:
  enabled: false
  from: ""

sort:
  enabled: true
  by: name

settings:
  anchor: true
  color: true
  default: true
  description: false
  escape: true
  hide-empty: false
  html: true
  indent: 2
  lockfile: true
  read-comments: true
  required: true
  sensitive: true
  type: true
